// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA60rXNNhTLeaqBAFTRVwo967mDKdkNcRs',
    appId: '1:129236384489:web:5c58b395b393f752b30e78',
    messagingSenderId: '129236384489',
    projectId: 'chatapp-d55b4',
    authDomain: 'chatapp-d55b4.firebaseapp.com',
    storageBucket: 'chatapp-d55b4.firebasestorage.app',
    measurementId: 'G-M9HSZTJTT1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrqV60NYdzjh6ntJN9hhj-ubYHLDzSsAU',
    appId: '1:129236384489:android:22d75552b806891fb30e78',
    messagingSenderId: '129236384489',
    projectId: 'chatapp-d55b4',
    storageBucket: 'chatapp-d55b4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCV1UhJ2NfCs1FRwA7q2bMlfzhgVJj0WUo',
    appId: '1:129236384489:ios:6c55e716a2bb7472b30e78',
    messagingSenderId: '129236384489',
    projectId: 'chatapp-d55b4',
    storageBucket: 'chatapp-d55b4.firebasestorage.app',
    iosBundleId: 'com.example.wharapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCV1UhJ2NfCs1FRwA7q2bMlfzhgVJj0WUo',
    appId: '1:129236384489:ios:6c55e716a2bb7472b30e78',
    messagingSenderId: '129236384489',
    projectId: 'chatapp-d55b4',
    storageBucket: 'chatapp-d55b4.firebasestorage.app',
    iosBundleId: 'com.example.wharapp',
  );
}
